
server:
  port: 8081
  servlet:
    context-path: /restaurant/api

spring:
  datasource:
    url: "jdbc:postgresql://dpg-d3s8lja4d50c738kfpfg-a.singapore-postgres.render.com:5432/db_res_105e"
    username: root
    password: LmvCJ8n9PQ8gzDcD8zGx11rGhfkjwK0v


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: "X7kP9mQ2vL8jY4tR6uI0oW5zA3xC1bF9hD7eJ3gK5mN8pQ1rT4vL6yI0oW2zX7cV9mB3rT6yI0oW5zA3xC1bF9hD7eJ3gK5mN8pQ1r"
  valid-duration: 43200